CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) UNIQUE NOT NULL
);

CREATE TABLE "levels" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) UNIQUE NOT NULL
);

CREATE TABLE "teachers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL,
  "last_name" varchar(20) NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(40) UNIQUE NOT NULL,
  "description" varchar(130) UNIQUE NOT NULL,
  "level_id" int,
  "teacher_id" int
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "last_name" varchar(50) NOT NULL,
  "email" varchar(50) UNIQUE NOT NULL,
  "password" varchar(20) UNIQUE NOT NULL,
  "course_id" int,
  "role_id" int
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) UNIQUE NOT NULL,
  "course_id" int
);

CREATE TABLE "course_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(40) UNIQUE NOT NULL,
  "url" varchar(150) UNIQUE NOT NULL,
  "categories_id" int
);

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("id") REFERENCES "users" ("course_id");

ALTER TABLE "teachers" ADD FOREIGN KEY ("id") REFERENCES "courses" ("teacher_id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level_id") REFERENCES "levels" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("id") REFERENCES "categories" ("course_id");

ALTER TABLE "course_video" ADD FOREIGN KEY ("categories_id") REFERENCES "categories" ("id");

INSERT INTO roles (name) VALUES ('student'), ('teacher'), ('administrator');

INSERT INTO levels (name) VALUES ('beginner'), ('middle'), ('advanced');

INSERT INTO teachers (name, last_name) VALUES ('Andrea', 'Perez'), ('Maria', 'Ospino'), ('Andres', 'Gutierrez');

INSERT INTO courses (title, description, level_id, teacher_id) VALUES ('Master en JavaScript', 'Aprende a Programar desde cero y Desarrollo Web con JavaScript, jQuery,JSON,Typescript', 3, 3), ('Marketing Digital', 'Aprenda Marketing Digital para crecer su negocio: Marketing de Redes Sociales, Facebook, SEO, YouTube, E-mail marketing', 1, 2), ('Master Diseño Digital con Adobe', 'Aprende y Crea Diseño Digital con Photoshop cc 2020 desde cero, Crea, Diseña Webs', 2, 1);

INSERT INTO categories (name, course_id) VALUES ('Desarrollo', 1), ('Marketing', 2), ('Diseño', 3);

INSERT INTO course_video (title, url, categories_id) VALUES ('Master en JavaScript', 'https://couresWebServ.com/courseMasterenJavaScript/', 1), ('Marketing digital', 'https://coureswebServ.com/courseMarketing digital/', 2), ('Master Diseño Digital con Adobe', 'https://coureswebServ.com/courseMaster Diseño Digital con Adobe/', 3);

INSERT INTO users (name, last_name, email, password, course_id, role_id ) VALUES ('Juan', 'Tovar', 'juan@gmail.com', 'qwER1234', 1, 1), ('Carlos', 'Orosco', 'carlos@gmail.com', 'asDF4567', 2, 1), ('Marcos', 'meza', 'marcos@gmail.com', 'zxCV7890', 3, 1), ('Andrea', 'Perez', 'andrea@gmail.com', '1597nlKJ', 2, 2), ('Maria', 'Ospino', 'maria@courseWebServ.com', 'poIU4568', 3, 2), ('Andres', 'Perez', 'andres@courseWebServ.com', 'df45YU78', 1, 2), ('Edgardo', 'Oñate', 'edgardo@courseWebServ.com.com', '486p9w!', 1, 3);
